import { useState } from 'react'
import type { User } from '@supabase/supabase-js'
import { paymentUrl, type ServicePlan } from '../lib/payments'
import { supabase } from '../lib/supabase'

export function SupportRequest({ plan, user, onClose, onRequireSignIn }: { plan: ServicePlan; user: User | null; onClose: () => void; onRequireSignIn: () => void }) {
  const [model, setModel] = useState(''), [summary, setSummary] = useState(''), [status, setStatus] = useState(''), [busy, setBusy] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!user) { onRequireSignIn(); return } if (!supabase) { setStatus('Cloud support is not configured yet. Add the Supabase environment values before accepting orders.'); return } const organizationId = import.meta.env.VITE_SERVICE_ORGANIZATION_ID; if (!organizationId) { setStatus('Service routing is not configured yet. Add the Agentics organization ID before accepting orders.'); return } setBusy(true); setStatus(''); try { const reference = `ares_${crypto.randomUUID().replaceAll('-', '')}_${plan.id}`; const { data, error } = await supabase.from('support_requests').insert({ user_id: user.id, organization_id: organizationId, plan_id: plan.id, device_model: model || null, issue_summary: summary, payment_reference: reference, status: 'awaiting_payment' }).select('id,payment_reference').single(); if (error) throw error; const url = paymentUrl(plan, data.payment_reference); if (!url) { setStatus(`Case ${data.id.slice(0, 8).toUpperCase()} was created. Add the matching HTTPS payment link to the environment before accepting payment.`); return } window.location.assign(url) } catch (error) { setStatus(error instanceof Error ? error.message : 'We could not create your support case.') } finally { setBusy(false) } }
  return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label="Open support case"><button className="close" onClick={onClose}>×</button><p className="eyebrow">{plan.name.toUpperCase()}</p><h3>Open a real support case</h3><p>The case is private. Payment unlocks technician work; it does not guarantee an unsafe or impossible repair.</p><form onSubmit={submit}><label>Phone model<input value={model} onChange={e => setModel(e.target.value)} placeholder="e.g. Galaxy S23" /></label><label>What happened?<textarea required value={summary} onChange={e => setSummary(e.target.value)} placeholder="When it began, what appears on screen, and what you have already tried." /></label><button className="primary wide" disabled={busy}>{busy ? 'Creating case…' : user ? 'Create case and continue to secure payment' : 'Sign in to create your case'}</button></form>{status && <small className="form-message">{status}</small>}</section></div>
}
