import { useEffect, useMemo, useState } from 'react'
import './App.css'
import './components/commerce.css'
import { diagnoseBootLoop, getNextQuestion, type BootLoopAnswers } from './lib/diagnosticEngine'
import { createSession, loadSession, persistSession } from './lib/sessionStore'
import type { DiagnosticSession, RiskLevel } from './types'
import type { User } from '@supabase/supabase-js'
import { currentUser, signOut } from './lib/auth'
import { AuthPanel } from './components/AuthPanel'
import { Pricing } from './components/Pricing'
import { SupportRequest } from './components/SupportRequest'
import type { ServicePlan } from './lib/payments'

const riskText: Record<RiskLevel,string>={safe:'Safe — no known data-loss risk',low:'Low risk — preserves personal data',medium:'Medium risk — use the support route shown',service_required:'Service required — hardware assessment recommended'}
const samsungGuide='https://www.samsung.com/us/support/troubleshoot/TSG10001948/'
type View='home'|'diagnosis'|'result'|'recovery'
function App(){
 const [view,setView]=useState<View>('home'),[session,setSession]=useState<DiagnosticSession|null>(null),[answers,setAnswers]=useState<BootLoopAnswers>({}),[model,setModel]=useState('Samsung Galaxy'),[notice,setNotice]=useState(''),[recoveryStep,setRecoveryStep]=useState(0),[recoveryStatus,setRecoveryStatus]=useState<'active'|'resolved'|'service'>('active'),[resetConsent,setResetConsent]=useState(false),[user,setUser]=useState<User|null>(null),[authOpen,setAuthOpen]=useState(false),[selectedPlan,setSelectedPlan]=useState<ServicePlan|null>(null)
 const report=useMemo(()=>diagnoseBootLoop(answers),[answers]), question=useMemo(()=>getNextQuestion(answers),[answers])
 useEffect(()=>{loadSession().then(s=>{if(s){setSession(s);setAnswers(s.answers as BootLoopAnswers);setModel(s.device.model);setView(s.status==='completed'?'result':'diagnosis')}})},[])
 useEffect(()=>{currentUser().then(setUser)},[])
 async function start(){const s=createSession(model);setSession(s);setAnswers({});setRecoveryStep(0);setRecoveryStatus('active');setView('diagnosis');await persistSession(s)}
 async function answer(v:boolean|'unknown'){if(!session||!question)return;const next={...answers,[question.id]:v};const s={...session,device:{...session.device,model},answers:next,evidence:diagnoseBootLoop(next).evidence,updatedAt:new Date().toISOString()};setAnswers(next);setSession(s);await persistSession(s)}
 async function finish(){if(!session)return;const s={...session,status:'completed' as const,updatedAt:new Date().toISOString()};setSession(s);await persistSession(s);setView('result')}
 const knox=()=>setNotice('Knox Guard guidance is a safety module: ARES can identify and explain a management/finance lock and route the owner to the legitimate provider. It never attempts a bypass.')
 return <main className="shell"><nav><button className="brand" onClick={()=>setView('home')}>◈ ARES <i>AI</i></button><div><a href="#method">How it works</a><a href="#services">Services</a><a href="#pro">ARES PRO</a>{user?<button className="account" onClick={async()=>{await signOut();setUser(null)}}>Sign out</button>:<button className="account" onClick={()=>setAuthOpen(true)}>Sign in</button>}</div></nav>
 {view==='home'&&<><section className="hero"><p className="eyebrow">AGENTICS · SMARTPHONE DIAGNOSTICS</p><h1>Find the cause.<br/><em>Protect the data.</em></h1><p>ARES turns symptoms into evidence, probable causes and the safest next action — starting with Samsung.</p><button className="primary" onClick={start}>Start a diagnosis <b>→</b></button><div className="signals"><span><b>Evidence first</b>Never guesses</span><span><b>Risk-aware</b>Data before drama</span><span><b>Samsung MVP</b>Boot Loop live</span></div></section>
 <section className="issues"><button className="issue featured" onClick={start}><span>↻</span><b>Boot loop</b><small>Restarts at the logo</small><i>Diagnose →</i></button><button className="issue" onClick={()=>setNotice('Thermal diagnostics are the next Samsung flow. The engine and data model already support it.')}><span>⌁</span><b>Overheating</b><small>Heat, battery & charging</small><i>Coming next</i></button><button className="issue" onClick={knox}><span>⌘</span><b>Knox Guard</b><small>Management-lock guidance</small><i>Safe guidance</i></button></section><Pricing onChoose={plan=>setSelectedPlan(plan)}/>
 {notice&&<aside className="notice">ⓘ {notice}<button onClick={()=>setNotice('')}>×</button></aside>}
 <section id="method" className="method"><p className="eyebrow">DIAGNOSTIC METHOD</p><div><h2>Not a chatbot.<br/>A diagnostic engine.</h2><ol><li><b>01</b><span><strong>Collect evidence</strong>Separate what a device shows from what is inferred.</span></li><li><b>02</b><span><strong>Reduce uncertainty</strong>Ask only questions that change the next decision.</span></li><li><b>03</b><span><strong>Choose the safest action</strong>Make data-loss risk visible before every recovery step.</span></li></ol></div></section></>}
 {view==='diagnosis'&&<section className="page"><button className="back" onClick={()=>setView('home')}>← Back to diagnostic lab</button><header><div><p className="eyebrow">ACTIVE SESSION</p><h2>Samsung Boot Loop</h2><small>Evidence-led assessment · {report.progress}% complete</small></div><div className="confidence">Confidence<strong>{report.confidence}%</strong><small>{report.confidenceLabel}</small></div></header><div className="progress"><i style={{width:`${report.progress}%`}}/></div><div className="grid"><section className="card question"><p className="eyebrow">DEVICE</p><label>Model (if known)<input value={model} onChange={e=>setModel(e.target.value)} placeholder="Samsung Galaxy S23"/></label>{question?<><p className="eyebrow next">NEXT BEST QUESTION</p><h3>{question.prompt}</h3><p>{question.helper}</p><div className="answers"><button onClick={()=>answer(true)}>Yes</button><button onClick={()=>answer(false)}>No</button><button onClick={()=>answer('unknown')}>I’m not sure</button></div></>:<><h3>We have enough evidence for a safe first recommendation.</h3><button className="primary wide" onClick={finish}>View diagnostic result →</button></>}<small className="privacy">This structured session is kept locally and syncs securely once Supabase and sign-in are configured.</small></section><aside className="card insight"><p className="eyebrow">LIVE ASSESSMENT</p><div className={`risk ${report.risk}`}>● {riskText[report.risk]}</div><h4>Probable causes</h4>{report.causes.map(c=><div className="cause" key={c.id}><span>{c.label}<i><em style={{width:`${c.probability}%`}}/></i></span><b>{c.probability}%</b></div>)}<h4>Current evidence</h4><ul>{report.evidence.length?report.evidence.map(e=><li key={e.id}>✓ {e.statement}<small>{e.kind}</small></li>):<li>Answer the first question to establish evidence.</li>}</ul></aside></div></section>}
 {view==='result'&&<section className="page result"><button className="back" onClick={()=>setView('home')}>← Back to diagnostic lab</button><p className="eyebrow">ARES DIAGNOSTIC RESULT</p><h2>Samsung Boot Loop</h2><small>Session {session?.id.slice(0,8).toUpperCase()} · {model}</small><div className="grid"><section className="card"><p className="eyebrow">PRIMARY SUSPECT</p><h3>{report.primary.label}</h3><div className="metrics"><span><b>{report.primary.probability}%</b> probability</span><span><b>{report.confidenceLabel}</b> confidence</span></div><p>The current assessment is probabilistic, not a confirmed repair diagnosis. It reflects the evidence recorded in this session.</p><div className={`risk ${report.risk}`}>● {riskText[report.risk]}<br/><small>The first recommended action does not instruct a data wipe.</small></div></section><section className="card plan"><p className="eyebrow">RECOMMENDED FIRST ACTION</p><h3>{report.action.title}</h3><p>{report.action.description}</p><ol>{report.action.steps.map(s=><li key={s}>{s}</li>)}</ol><aside>⚠ {report.action.warning}</aside><button className="primary wide" onClick={()=>{setRecoveryStep(0);setRecoveryStatus('active');setResetConsent(false);setView('recovery')}}>{report.risk==='service_required'||answers.securityMessage===true?'Open safe support path':'Start guided recovery'} →</button></section></div></section>}
 {view==='recovery'&&<RecoveryRunbook model={model} risk={report.risk} security={answers.securityMessage===true} step={recoveryStep} setStep={setRecoveryStep} status={recoveryStatus} setStatus={setRecoveryStatus} resetConsent={resetConsent} setResetConsent={setResetConsent} onBack={()=>setView('result')} onHome={()=>{setView('home');setNotice(recoveryStatus==='resolved'?'Great — recovery outcome recorded locally. Monitor the phone before restoring all apps.':'Session saved. ARES has recorded the safest next path.')}}/>}
 {authOpen&&<AuthPanel onClose={()=>setAuthOpen(false)} onDone={async()=>{setUser(await currentUser());setAuthOpen(false)}}/>}{selectedPlan&&<SupportRequest plan={selectedPlan} user={user} onClose={()=>setSelectedPlan(null)} onRequireSignIn={()=>setAuthOpen(true)}/>}<footer id="pro"><b>ARES AI</b><span>Built by Agentics · Diagnostic and legitimate recovery guidance. No security bypasses.</span><small>ARES PRO and the desktop USB agent are prepared for the next release.</small></footer></main>}

function RecoveryRunbook({model,risk,security,step,setStep,status,setStatus,resetConsent,setResetConsent,onBack,onHome}:{model:string;risk:RiskLevel;security:boolean;step:number;setStep:(n:number)=>void;status:'active'|'resolved'|'service';setStatus:(s:'active'|'resolved'|'service')=>void;resetConsent:boolean;setResetConsent:(v:boolean)=>void;onBack:()=>void;onHome:()=>void}){
 const blocked=risk==='service_required'||security
 if(status==='resolved')return <section className="page recovery"><button className="back" onClick={onHome}>← Back to diagnostic lab</button><div className="outcome good"><p className="eyebrow">RECOVERY OUTCOME</p><h2>Boot restored</h2><p>Excellent. Keep the phone connected to an approved charger, back up important data, and install outstanding official updates only after it remains stable.</p><ol><li>Back up data with Samsung/Google cloud or Smart Switch.</li><li>Monitor it for 24 hours before reinstalling recent apps.</li><li>If restarting returns, reopen this case and record when it happens.</li></ol><button className="primary" onClick={onHome}>Finish session</button></div></section>
 if(blocked)return <section className="page recovery"><button className="back" onClick={onBack}>← Back to result</button><div className="outcome warning"><p className="eyebrow">SAFE ESCALATION</p><h2>{security?'Management or account restriction detected':'Potential hardware risk detected'}</h2><p>{security?'Do not attempt firmware, account or lock bypasses. The device owner should contact the provider named in the on-screen message, the seller/finance provider, or Samsung support.':'Because there is abnormal heat or Recovery Mode cannot stay stable, flashing, repeated charging and reset attempts could worsen the fault or lose data.'}</p><ol>{security?<><li>Photograph the exact message and any reference number.</li><li>Contact the carrier, retailer, finance provider or organisation named.</li><li>Use a Samsung-supported channel if no provider is identified.</li></>:<><li>Disconnect charging accessories if the phone is hot; let it cool on a non-flammable surface.</li><li>Do not open the device or attempt a battery replacement unless qualified.</li><li>Arrange an authorised Samsung or qualified repair-centre assessment.</li></>}</ol><button className="primary" onClick={()=>{setStatus('service');onHome()}}>Record service referral</button></div></section>
 const steps=[
  {title:'1. Do a safe forced restart',text:'Use an approved Samsung charger if the battery is low. Then hold Volume Down + Side/Power button together until the Samsung logo appears. This can take up to 60 seconds.',note:'If the phone is hot, skip this and arrange service instead.',yes:'It booted normally',no:'It still loops'},
  {title:'2. Try Safe Mode only if the phone reaches the Samsung logo',text:'Power the phone on. When the Samsung logo appears, hold Volume Down until it reaches the lock screen. “Safe mode” should appear at the bottom.',note:'Safe Mode disables downloaded apps. If it boots here, uninstall the most recently added or suspicious apps, then restart normally.',yes:'It boots in Safe Mode',no:'It will not boot Safe Mode'},
  {title:'3. Use Samsung Smart Switch on a computer',text:'Connect the phone using the supplied/approved USB cable. In official Samsung Smart Switch for Windows or macOS, let the program detect the device and offer an official software update if available.',note:'Do not disconnect the USB cable or use the device while an official update is running.',yes:'Update completed and it boots',no:'Not detected or no update'},
  {title:'4. Last option: factory reset',text:'This may resolve a software boot loop, but it erases all data. Only continue if no backup/recovery option remains and the owner knows the Google/Samsung account credentials previously used on the phone.',note:'ARES does not execute resets. It directs the owner to Samsung’s documented recovery process for their exact model.',yes:'I accept data loss and want Samsung instructions',no:'I do not accept data loss'},
 ]
 const current=steps[step]
 const next=(ok:boolean)=>{if(ok&&step<3){setStatus('resolved');return}if(step===3){if(ok&&resetConsent)window.open(samsungGuide,'_blank','noopener,noreferrer');setStatus('service');return}setStep(step+1)}
 return <section className="page recovery"><button className="back" onClick={onBack}>← Back to result</button><p className="eyebrow">GUIDED RECOVERY · {model}</p><h2>Resolve the boot loop safely</h2><p className="runbook-intro">ARES cannot repair the hardware from the browser. It can, however, lead the owner through verified low-risk actions and stop before data loss or unsafe work.</p><div className="recovery-progress">{steps.map((_,index)=><i className={index<=step?'on':''} key={index}/>)}</div><section className="card runbook"><p className="eyebrow">{current.title}</p><h3>{current.text}</h3><p>{current.note}</p>{step===3&&<label className="consent"><input type="checkbox" checked={resetConsent} onChange={e=>setResetConsent(e.target.checked)}/> I understand that a factory reset erases all local data and I have the required account credentials.</label>}<div className="answers"><button onClick={()=>next(true)} disabled={step===3&&!resetConsent}>{current.yes}</button><button onClick={()=>next(false)}>{current.no}</button></div><a className="official" href={samsungGuide} target="_blank" rel="noreferrer">Open Samsung’s official boot-loop guide ↗</a></section></section>
}
export default App
